ShopatBanaturalPortal/Models/InventoryItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Globalization;
using System.ComponentModel.DataAnnotations;

namespace ShopatBanaturalPortal.Models
{
    public class InventoryItem
    {
        public int ID { get; set; }
        public string ItemName {get; set; }
        public int ItemNumber { get; set; }
        public int SoldtoDate { get; set; }
        public int SoldthisMonth { get; set; }
        public int SoldthisYear { get; set; }
        public int QuantityLeft { get; set; }
        public string LastShipmentRecieved { get; set; }

        //medicine, food, herb
        public string Type { get; set; }
        public string ShipmentHistory { get; set; }
        public string GeneralDescription { get; set; }
        public string TransactionHistory { get; set; }

        //other qualities
        public float Price { get; set; }
        public string CustomID { get; set; }
        public string Brand { get; set; }


    }

    public class InventoryItemDbContext : System.Data.Entity.DbContext
    {
        
        public InventoryItemDbContext() : base("DefaultConnection")
        {

        }
        

        public DbSet<InventoryItem> InventoryItemDatabase { get; set; }
    }

}

ShopatBanaturalPortal/Controllers/InventoryItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopatBanaturalPortal.Models;
using System.Text;
using System.Text.RegularExpressions;

namespace ShopatBanaturalPortal.Controllers
{
    public class InventoryItemsController : Controller
    {
        private InventoryItemDbContext db = new InventoryItemDbContext();

        // GET: InventoryItems
        public ActionResult Index(string searchString = "")
        {
            if(searchString != null)
            {
                ViewBag.SearchString = searchString;
            }
            

            var ItemsSelected = from m in db.InventoryItemDatabase
                                  orderby m.Type, m.CustomID
                                  select m;



            if (!String.IsNullOrEmpty(searchString))
            {
                ItemsSelected = from m in db.InventoryItemDatabase
                                where m.ItemName.Contains(searchString)  || m.Type.Contains(searchString)  || (m.QuantityLeft.ToString()).Contains(searchString) || m.Brand.Contains(searchString) || m.CustomID.Contains(searchString) || m.GeneralDescription.Contains(searchString)
                                orderby m.Type, m.QuantityLeft
                                select m;
            }

            return View(ItemsSelected);
        }

        public ActionResult ExportExcel(string searchString)
        {
            searchString = searchString + "";

            var ItemsSelected = (from m in db.InventoryItemDatabase
                                 orderby m.Type, m.CustomID
                                 select m).ToList();



            if (!String.IsNullOrEmpty(searchString))
            {
                ItemsSelected = (from m in db.InventoryItemDatabase
                                where m.ItemName.Contains(searchString) || m.Type.Contains(searchString) || (m.QuantityLeft.ToString()).Contains(searchString) || m.Brand.Contains(searchString) || m.CustomID.Contains(searchString) || m.GeneralDescription.Contains(searchString)
                                orderby m.Type, m.QuantityLeft
                                select m).ToList();
            }

            List<InventoryItem> ReadyToExport = ItemsSelected;
            TempData["ReadyToExportSelection"] = ReadyToExport;
            return RedirectToAction("ExportToExcel");
        }

        [HttpGet]
        public FileContentResult ExportToExcel()
        {
            List<InventoryItem> ReadyToexport = new List<InventoryItem>();
            ReadyToexport = (List<InventoryItem>)TempData["ReadyToExportSelection"];
            string[] columns = { "ItemName", "Brand", "CustomID", "QuantityLeft", "Price", "Type", "GeneralDescription", "SoldtoDate" };
            byte[] filecontent = ExcelExportHelper.ExportExcel(ReadyToexport, "Inventory", false, columns);
            return File(filecontent, ExcelExportHelper.ExcelContentType, "Inventory_Report_"+DateTime.Now.DayOfYear + "_"+ DateTime.Now.Year +".xlsx");
        }
        public ActionResult ChartsIndex(string searchString)
        {

            var ItemsSelected = from m in db.InventoryItemDatabase
                                orderby m.Type, m.CustomID
                                select m;



            if (!String.IsNullOrEmpty(searchString))
            {
                ItemsSelected = from m in db.InventoryItemDatabase
                                where m.ItemName == searchString || m.Type == searchString || (m.QuantityLeft.ToString()).Contains(searchString) || m.Brand == searchString || m.CustomID == searchString
                                orderby m.Type, m.QuantityLeft
                                select m;
            }

            return View(ItemsSelected);
        }

        public ActionResult TransactionHistory(int ID)
        {
            var SelectedItem = from S in db.InventoryItemDatabase
                               where S.ID == ID
                               select S;
            InventoryItem ItemModel = (InventoryItem)SelectedItem.First<InventoryItem>();

            string[] History = ItemModel.TransactionHistory.Split('*');
            ViewBag.Model = ItemModel;
            return View(History);
        }
        public ActionResult ShipmentHistory(int ID)
        {
            var SelectedItem = from S in db.InventoryItemDatabase
                               where S.ID == ID
                               select S;
            InventoryItem ItemModel = (InventoryItem)SelectedItem.First<InventoryItem>();

            string[] History = ItemModel.ShipmentHistory.Split('*');
            return View(History);
        }

        // GET: InventoryItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryItem inventoryItem = db.InventoryItemDatabase.Find(id);
            if (inventoryItem == null)
            {
                return HttpNotFound();
            }
            return View(inventoryItem);
        }

        // GET: InventoryItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InventoryItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string Type, [Bind(Include = "ID,CustomID,Brand,ItemName,Price,QuantityLeft,Type,GeneralDescription")] InventoryItem inventoryItem)
        {
            if (ModelState.IsValid)
            {
                inventoryItem.Type = Type;
                inventoryItem.LastShipmentRecieved = "Not Yet Stocked";
                inventoryItem.ItemNumber = inventoryItem.ID;
                inventoryItem.ItemName = inventoryItem.ItemName.ToUpper();
                inventoryItem.Brand = inventoryItem.Brand.ToUpper();

                db.InventoryItemDatabase.Add(inventoryItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(inventoryItem);
        }

        // GET: InventoryItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryItem inventoryItem = db.InventoryItemDatabase.Find(id);
            if (inventoryItem == null)
            {
                return HttpNotFound();
            }
            return View(inventoryItem);
        }

        // POST: InventoryItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CustomID,Brand,ItemName,ItemNumber,SoldtoDate,SoldthisMonth,SoldthisYear,QuantityLeft,LastShipmentRecieved,Type,ShipmentHistory,GeneralDescription,TransactionHistory,Price")] InventoryItem inventoryItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inventoryItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(inventoryItem);
        }

        

        public ActionResult UpdateShipments(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryItem inventoryItem = db.InventoryItemDatabase.Find(id);
            if (inventoryItem == null)
            {
                return HttpNotFound();
            }
            return View(inventoryItem);
        }

        // POST: InventoryItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateShipments(int ID, string Restock)
        {
            var SelectedItem = from S in db.InventoryItemDatabase
                               where S.ID == ID
                               select S;
            InventoryItem ItemModel = (InventoryItem)SelectedItem.First<InventoryItem>();

            if (ModelState.IsValid)
            {
                ItemModel.LastShipmentRecieved = DateTime.Now.ToShortDateString();
                ItemModel.QuantityLeft = ItemModel.QuantityLeft + Convert.ToInt32(Restock);
                //split by **
                ItemModel.ShipmentHistory = ItemModel.ShipmentHistory + "[Restocked] " + Restock + " " + ItemModel.ItemName + ". [Restocked on] " + DateTime.Now.ToShortDateString() + "*";


                db.Entry(ItemModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ItemModel);
        }

        public ActionResult ItemSold(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryItem inventoryItem = db.InventoryItemDatabase.Find(id);
            if (inventoryItem == null)
            {
                return HttpNotFound();
            }
            return View(inventoryItem);
        }

        // POST: InventoryItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

ShopatBanaturalPortal/Views/InventoryItems/ChartsIndex.cshtml
@model IEnumerable<ShopatBanaturalPortal.Models.InventoryItem>

@{
    ViewBag.Title = "Index";
}

<h2>Charts</h2>
<br />


<div>

    <div class="form-group col-sm-6 col-md-6 col-lg-6">
        @using (Html.BeginForm())
        {
            <p>
                Search @Html.TextBox("SearchString", null, new { @class = "form-control" })
                <input type="submit" value="Search" class="btn btn-primary btn-sm" /> <br /> <br />
            </p>
        }
    </div>

</div>
<br />

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Store ID
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            <span class="alert-danger">@Html.DisplayFor(modelItem => item.CustomID)</span>
        </td>
        <td>
            @Html.ActionLink("Generate Chart", "GenerateChart", new { id = item.ID })
        </td>
    </tr>
}

</table>

ShopatBanaturalPortal/Views/InventoryItems/Create.cshtml
@model ShopatBanaturalPortal.Models.InventoryItem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InventoryItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, "Item Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, "Brand", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityLeft, "Initial Left", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityLeft, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantityLeft, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Price ($)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <br />
                <select id="Type" name="Type">
                    <option value=""> </option>
                    <option value="Medicine">Medicine</option>
                    <option value="Herb">Herb</option>
                    <option value="Frozen Food">Frozen Food</option>
                    <option value="Refrigerated Food">Refrigerated Food</option>
                    <option value="Dry Food">Dry Food</option>
                    <option value="Canned Food">Canned Food</option>
                    <option value="Snacks">Snacks</option>
                    <option value="Other">Other</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomID, "Store ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneralDescription, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GeneralDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GeneralDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShopatBanaturalPortal/Views/InventoryItems/Delete.cshtml
@model ShopatBanaturalPortal.Models.InventoryItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

<h4>Inventory Item</h4>
<hr />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GeneralDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoldtoDate)
        </th>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.ItemName)
        </td>
        <td>
            @Html.DisplayFor(model => model.GeneralDescription)
        </td>
        <td>
            @Html.DisplayFor(model => model.SoldtoDate)
        </td>
    </tr>
</table>

    <div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

ShopatBanaturalPortal/Views/InventoryItems/Details.cshtml
@model ShopatBanaturalPortal.Models.InventoryItem

@{
    ViewBag.Title = "Details";
}

<h2>Pending...</h2>
Not Active
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShopatBanaturalPortal/Views/InventoryItems/Edit.cshtml
@model ShopatBanaturalPortal.Models.InventoryItem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="col-sm-12 col-md-12 col-lg-12">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>InventoryItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, "Item Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, "Brand", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.QuantityLeft)
        @Html.HiddenFor(model => model.ShipmentHistory)
        @Html.HiddenFor(model => model.TransactionHistory)
        @Html.HiddenFor(model => model.LastShipmentRecieved)

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Price ($)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomID, "Store ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneralDescription, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GeneralDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GeneralDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}
</div>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShopatBanaturalPortal/Views/InventoryItems/ExportExcel.cshtml
@{
    ViewBag.Title = "ExportExcel";
}

<h2>ExportExcel</h2>

ShopatBanaturalPortal/Views/InventoryItems/ExportToExcel.cshtml
@{
    ViewBag.Title = "ExportExcel";
}

<h2>ExportExcel</h2>

ShopatBanaturalPortal/Views/InventoryItems/GenerateChart.cshtml
@using ShopatBanaturalPortal.Models;
@model IList<string>

@{
    ViewBag.Title = "GenerateChart";
}

<h2>Generate Chart</h2>
<br /><br />
<u>Incomplete. Currently only registers number of transactions. Not number of items sold. Each square is a transaction.</u>
<br /><br />
@{
    var I_item = (InventoryItem)ViewBag.Model;
    DateTime Start = DateTime.Parse(Model[0]);
    DateTime End = DateTime.Now;
    DateTime TraverseDays = Start;
    int TotalDays = (End - Start).Days + 1;

        for (int i = 0; i < TotalDays; i++)
        {
            <div class="col-md-2 col-lg-2">
                <span>@TraverseDays.ToShortDateString() </span>
            </div>
            <div class="col-md-10 col-lg-10">
                @{
                    <span><strong>|</strong></span>
                    while (Model.Any() && Model[0] == TraverseDays.ToShortDateString())
                    {
                        Model.Remove(Model[0]);
                        <span>
                            <img src="~/Content/PixelSprite.png" />
                        </span>
                    }
                }

            </div>
            <br />
            TraverseDays = TraverseDays.AddDays(1);
        }



}

<br /><br />

ShopatBanaturalPortal/Views/InventoryItems/Index.cshtml
@model IEnumerable<ShopatBanaturalPortal.Models.InventoryItem>

@{
    ViewBag.Title = "Index";
}

<h2>Inventory Manifest</h2>
<br />


<div>

    <div class="form-group col-sm-6 col-md-6 col-lg-6">
        @using (Html.BeginForm())
        {
            <p>
                Search @Html.TextBox("SearchString", null, new { @class = "form-control" })
                <input type="submit" value="Search" class="btn btn-primary btn-sm" /> <br /> <br />
            </p>
        }
    </div>

    <div class="form-group col-sm-6 col-md-6 col-lg-6">
        <p>
            <br />
            @Html.ActionLink("New Inventory Item", "Create", "InventorItems", new { @class = "btn btn-success" })
        </p>
    </div>

</div>
<br />

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Brand
        </th>
        <th>
            Store ID
        </th>
        <th>
            Quantity Left
        </th>
        <th>
            Price
        </th>
        <th>
            Type
        </th>
        <th>
            Description
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            <em>@Html.DisplayFor(modelItem => item.Brand)</em>
        </td>
        <td>
            <span class="alert-danger">@Html.DisplayFor(modelItem => item.CustomID)</span>
        </td>
        <td>
            <strong>
            <em>@Html.DisplayFor(modelItem => item.QuantityLeft)</em>
            </strong> 
        </td>
        <td>
            @{
                string display = item.Price.ToString("0.00");
                <span>@display</span>
            }$
        </td>
        <td>
            <em>@Html.DisplayFor(modelItem => item.Type)</em>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GeneralDescription)
        </td>
        <td style="text-align:center;">
            
            <span style="color: lightgreen">@Html.ActionLink("Register Transaction", "ItemSold", new { ID = item.ID }, new { @class = "btn btn-info btn-xs" })</span><br />
            <span style="color: lightgreen"> @Html.ActionLink("Transaction History", "TransactionHistory", new { ID = item.ID }) </span>
           


        </td>
        <td style="text-align:center;">
            <span style="color: lightgreen">@Html.ActionLink("Register Shipment", "UpdateShipments", new { ID = item.ID }, new { @class= "btn btn-info btn-xs" })</span><br />
            <span style="color: lightgreen">@Html.ActionLink("Shipment History", "ShipmentHistory", new { ID = item.ID })</span>
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", "InventoryItems", new { id = item.ID }, new { @class = "text-danger btn btn-warning btn-xs" }) |
        </td>
    </tr>
}

</table>

<br />
<div class="form-group col-sm-6 col-md-6 col-lg-6">
    <p>
        <br />
        @Html.ActionLink("Export", "ExportExcel", "InventoryItems", new { searchString = (string)ViewBag.SearchString }, new { @class = "btn btn-info" })
    </p>
</div>
<br /><br /><br />

ShopatBanaturalPortal/Views/InventoryItems/ItemSold.cshtml
@model ShopatBanaturalPortal.Models.InventoryItem

@{
    ViewBag.Title = "Edit";
}

<h2>Inventory</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Update Inventory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.Label("System ID:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="ID" style="width:100px; background-color: #E8DAEF" readonly="readonly" type="text" name="ID" value=@Model.ID>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CustomID, "Store ID: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.CustomID)
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, "Name:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ItemName)
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Price:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Price) $
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.QuantityLeft, "Quantity Left:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.QuantityLeft)
            </div>
        </div>
        <hr />
        <br />
        <div class="form-group">
            @Html.Label("Amount Sold:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="Sold" style="width:100px; background-color: lemonchiffon" type="text" name="Sold">
            </div>
        </div>
        <br />
        @{
            if (Model.QuantityLeft > 0)
            {
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit Update" class="btn btn-default" />
                    </div>
                </div>
            }
            else
            {
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Out of Stock" class="btn btn-default" />
                    </div>
                </div>
            }
        }

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}